// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contribution',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contribution',
        },
      ],
    },
  ],
};

export default sidebars;
